# Generated by Django 4.0.5 on 2022-08-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='vote_at',
            new_name='poll',
        ),
    ]
